function ACQ = importMethFile2(filename, dataLines)
    %IMPORTFILE Import data from a text file
    %  ACQ = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
    %  default selection.  Returns the data as a table.
    %
    %  ACQ = IMPORTFILE(FILE, DATALINES) reads data for the specified row
    %  interval(s) of text file FILENAME. Specify DATALINES as a positive
    %  scalar integer or a N-by-2 array of positive scalar integers for
    %  dis-contiguous row intervals.
    %
    %  Example:
    %  ACQ = importfile("/MATLAB Drive/OPTIMISATION SEQUENCE TEST/OPTIMISATION SEQUENCE TEST/OPTIMISATION SEQUENCE0001.D/ACQ.M/ACQ.TXT", [14, 14]);
    %
    %  See also READTABLE.
    %
    % Auto-generated by MATLAB on 16-Nov-2020 13:37:21
    
    %% Input handling
    
    % If dataLines is not specified, define defaults
    if nargin < 2
        dataLines = [1, Inf];
    end
    
    %% Set up the Import Options and import the data
    opts = fixedWidthImportOptions("NumVariables", 2,"Encoding", "UTF16-LE");
    
    % Specify range and variable widths
    opts.DataLines = dataLines;
    opts.VariableWidths = [78, 15];
    
    % Specify column names and types
    opts.VariableNames = ["Data", "Var2"];
    opts.SelectedVariableNames = "Data";
    opts.VariableTypes = ["string", "string"];
    
    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    
    % Specify variable properties
    opts = setvaropts(opts, ["Data", "Var2"], "WhitespaceRule", "preserve");
    opts = setvaropts(opts, ["Data", "Var2"], "EmptyFieldRule", "auto");
    
    % Import the data
    ACQ = readtable(filename, opts);
    
end